version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  unit-tests:
    docker:
      - image: circleci/node:8.11.3

    steps:
      - checkout
      - run: yarn
      - run: yarn run test

workflows:
  test:
    jobs:
      - unit-tests
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
