version: 2.1

jobs:
  unit-tests:
    docker:
      - image: circleci/node:8.11.3

    steps:
      - checkout
      - run: yarn
      - run: yarn run test

  eslint:
    docker:
      - image: circleci/node:8.11.3

    steps:
      - checkout
      - run: yarn
      - run: yarn run lint

workflows:
  test:
    jobs:
      - unit-tests
      - eslint